### ISSUE TITLE
为什么Software fps才25？

### ISSUE THREAD

**Issue by xltangcs** [Godfly666/lenet_hls_pynq#1]
你好，想问问readme说的software 帧率25是在hls内仿真的帧率吗？
cpu不能这么慢吧

**Comment by hfwang132** [comment]
是pynq-z2上的cpu。你可以编译cpp代码运行测试一下

**Comment by xltangcs** [comment]
你好，我进行了测试并看了你的report
发现你这里software 应该指的是在hls点 c 仿真之后的结果
我不确定这是不是真的运行在zynq的cpu上
此外，下面这张图是全精度software（ c 仿真）的结果
![image](https://github.com/user-attachments/assets/19009f4e-665f-437c-8d08-d4a7088b4653)
下面这张是量化后software的结果
![fde2db66b6e7b507147e610496b3e4f](https://github.com/user-attachments/assets/df5bbff2-c980-434d-b188-6dda80792a64)
应该是量化后的结果接近你说的software 25fps（但是我目前还是不知道为什么量化后 software 更慢）

此外，我编译综合得到ip核，生成bit流后在pynq上进行了测试，我用的板子是ZYNQ ZC706
结果是单张图片71.22ms，采用你的双buffer就行验证单张71.17ms，约14fps，均远低于417fps
![image](https://github.com/user-attachments/assets/390b82bb-1846-44c5-ac4f-647d62eb2289)

不知道哪里可能有问题，有所打扰，还望解答~

**Comment by xltangcs** [comment]
你好，又发现和FPGA时钟频率有关
![image](https://github.com/user-attachments/assets/05489eba-6207-4c57-9677-cdf3ba8a2d3b)
但是感觉还差点，想优化到2ms，还有有什么建议嘛

**Comment by hfwang132** [comment]
1. software 的 25fps 不是 vitis hls 仿真的，是在 target 上编译运行的
2. 这里量化主要是降低面积，不是降低推理时间
3. 量化后仿真肯定更慢，因为用了特殊的数据结构
4. ip 核推理慢一般是 hls 的优化指令不对，可能是 vitis hls 版本问题。可以在 vitis hls 里检查关键路径里的数据流有没有按照预期方式运行，没有的话可以添加优化指令
